### ISSUE TITLE
Bump Laravel Package Dependencies can append duplicate constraints

### ISSUE THREAD

**Issue by tshafer** [laravel-shift/workbench-issues#10]
Mac Big Sur 11.4
Version 0.3.1

**Describe the bug**
Bump Laravel Package Dependencies can append duplicate constraints

**To Reproduce**
Select a project and run Bump Laravel Package Dependencies twice

<img width="489" alt="Screen Shot 2021-07-07 at 6 29 23 PM" src="https://user-images.githubusercontent.com/299464/124848216-43eeca80-df51-11eb-9618-5d69733be1aa.png">

**Comment by jasonmccreary** [comment]
@tshafer, thanks for reporting.

While this is indeed a bug, you likely didn't mean to run the "Laravel Package Dependencies" task. This task is for Laravel Packages. From the screenshot, yours appears to be a Laravel application. If so, you should run the "Bump Laravel Dependencies" task instead. It does not have an `append` option and would avoid the issue.

**Comment by jasonmccreary** [comment]
This should be resolved in the latest release (0.5.2). Let us know if you still see a problem.
