### ISSUE TITLE
Code Format: Custom => Also check new config file .php-cs-fixer.php

### ISSUE THREAD

**Issue by proclame** [laravel-shift/workbench-issues#11]
**What would you like to do?**
At this moment, the custom code format "workbench" only checks the existence of .php_cs, and uses it (correctly) if it does exist.

Since PHP CS Fixer v2.19.0 it supports using .php-cs-fixer.php as the config file, and since v3 the old (.php_cs) file name is no longer supported.

Would be great if both file names could be checked and can be used.

**Comment by jasonmccreary** [comment]
@proclame, now that 3.0 is stable and more widely adopted, we will be bumping our support. And likely adding a task to help those running v2 to upgrade their configs. 🔥

**Comment by jasonmccreary** [comment]
Shift now uses PHP CS Fixer 3.0 underneath. We never got around to finishing a converter. But I expect most have upgraded now. So long as you're ruleset is 3.0 compatible, Shift will find it and use it.
