### ISSUE TITLE
Suggestion: Ability to see Docker Setup Instructions after first-installation

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel-shift/workbench-issues#12]
**What would you like to do?**
I installed Docker for Win10 via WSL, but after rebooting I needed to recheck the setup instructions / articles as running Docker isn't quite working for me yet. My problem, not yours. (I'll solve it.) It would have been nice to be able to reference those setup instructions / references again within Workbench without having to Google. Uninstalling the program and reinstalling didn't work [to reshow the onboarding instructions].

**Comment by jessarcher** [comment]
Hey @BrandonSurowiec, thanks for the feedback!

Was there a particular reference you found helpful? We could include a link to it in the onboarding for Windows users.

**Comment by BrandonSurowiec** [comment]
I think you included all the relevant links, but I can't remember. I skipped the WSL setup as I was checking things out and didn't have time. So that is what I needed to go back and do, but it had been a few days and I couldn't remember what part of the setup I didn't do yet.

The app didn't have a way to pull up the onboarding instructions again.

**Comment by jasonmccreary** [comment]
@BrandonSurowiec, do you think adding the same Docker setup link in the Help menu would work?

**Comment by BrandonSurowiec** [comment]
@jasonmccreary That would be perfect.

**Comment by jasonmccreary** [comment]
@BrandonSurowiec awesome. We'll get this added in our next patch release. Probably tomorrow.

**Comment by jasonmccreary** [comment]
Added in release 0.3.2.
