### ISSUE TITLE
Fatal error on null-coalesce task

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#14]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.3.2.0

**Describe the bug**
Got a fatal error when running the task

**To Reproduce**
1. open workbench
2. select project
3. Run php/null-coalesce task

```
Fatal error: Cannot redeclare dump_node() (previously declared in /root/.composer/vendor/rector/rector/vendor/scoper-autoload.php:3303) in /project/vendor/rector/rector/src/functions/node_helper.php on line 9
Failed to run rector: adopt-null-coalesce: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/AdoptNullCoalesce.php(18): Shift\Tasks\Workbench\AdoptNullCoalesce->rector('/opt/shift/reso...')
#1 phar:///opt/shift/workbench/workbench.php(95): Shift\Tasks\Workbench\AdoptNullCoalesce->perform()
#2 /opt/shift/workbench(9): require('phar:///opt/shi...')
#3 {main}
--------------
```

The section was collapsed with the green checkmark so for I while I didn't know what had happened or why it was taking long

![image](https://user-images.githubusercontent.com/6376814/125456647-cf9a420c-a610-499b-84a4-da0d0a8f9c93.png)

![image](https://user-images.githubusercontent.com/6376814/125456688-82ce45ff-0430-4239-954b-944231f86de1.png)

**Comment by jasonmccreary** [comment]
This is likely a conflict with your local Rector dependency. We're working to protect around local installs as the Workbench itself uses some.

In the meantime, you may try temporarily removing your development dependencies. You may do so by remove the `vendor` folder and running `composer install --no-dev`. Additional detail is in [this issue thread](https://github.com/laravel-shift/workbench-issues/issues/7#issuecomment-873413729).
