### ISSUE TITLE
No changes made on task laravel/request-injection, warning thrown

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#15]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.3.2.0

**Describe the bug**
log shows this error

`Warning: foreach() argument must be of type array|object, null given in phar:///opt/shift/workbench/src/Tasks/Laravel/Fixer/RequestAccess.php on line 38`

No files were changed.

**To Reproduce**
1. open workbench
2. select project
3. Run laravel/request-injection

(I followed the instructions here https://github.com/laravel-shift/workbench-issues/issues/14#issuecomment-879078285)

![Workbench_jqLk0tUaCk](https://user-images.githubusercontent.com/6376814/125464746-c650bfc3-5a8a-404b-b1dc-37f803635985.png)

This piece of code should have had the task applied, right?

![cwE3rPpSQT](https://user-images.githubusercontent.com/6376814/125464615-238dc4f2-769c-4120-9cf2-db7426b1553b.png)

**Comment by jasonmccreary** [comment]
Would you be willing to run this via the [cloud-based Workbench](https://laravelshift.com/workbench). It will give me more insight into the error and hopefully help me determine a patch.

You may comment back with the build number or email it to support.

**Comment by ordago** [comment]
Sure, it's build #1667.

**Comment by ordago** [comment]
It went through on the cloud version.

![image](https://user-images.githubusercontent.com/6376814/125473767-877df676-876d-439b-a1ca-d19c2ad06af0.png)

The `$request` variable is out of scope there, right?

**Comment by jasonmccreary** [comment]
Yes, this is actually a boundary case for Shift. It changes it, but does not inject the variable into the closure's scrope.

**Comment by jasonmccreary** [comment]
@ordago, looking at this more closely, it seems the cloud-based Workbench ran successfully for you (aside from the boundary case above).

We'll continue to look into those for the Desktop app, but at least that gives you a start.

**Comment by jasonmccreary** [comment]
@ordago, we found the issue here. We'll push a patch tomorrow once we have a few other items to bundle.

**Comment by jasonmccreary** [comment]
This has been updated in the latest release (0.4.2). Let us know if you still see the issue.

**Note:** The references within closures is a separate issue which we will address in the future.

**Comment by ordago** [comment]
Hi Jason, I ran it again. I didn't merge the cloud version of the task because I ran other tasks in between.

It made no changes again. Using 0.4.2.0

![image](https://user-images.githubusercontent.com/6376814/125694265-621339f9-e0e1-4ba3-bba1-e830cfab505e.png)

**Comment by jasonmccreary** [comment]
@ordago, would you mind running the cloud-based version again, just to confirm it still makes the changes?

**Comment by ordago** [comment]
@jasonmccreary Sure, here it is. Build #1674.

This time the cloud didn't make any changes. But apparently I did merge the previous request 😅. 

It seems there are some edge cases so I was finding examples of request() in controllers.

If you want I can get some examples.

**Comment by ordago** [comment]
`return $query->whereRaw($q, [$start, $end, $start, $end, round(request('absenteeism', $absenteeismPercent) / 100, 2)]);`

This is in an invokable controller and it also uses `request('key', $default)` instead of `request()->get('key', $default)`.

The rest of the examples are in a long private helper method on a controller.

**Comment by jasonmccreary** [comment]
Ok. We'll note these edge cases. However, since you already merged the changes and did not receive the same error I am going to assume our fix worked. At least for this issue. 😅
