### ISSUE TITLE
Transform @lang blade directive to {{}} equivalent

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#16]
**What would you like to do?**
It's an opinionated task but it would follow Laravel's example as they removed mentions of @lang last December:

https://github.com/laravel/docs/commit/0ab96f0b7c55966f5402b99e37268a0e9dacd03e#diff-737a3cc79367bf5e9f9254b03ef0b5af518571a70fda75e7855cf5f4fe77093eL116-L122

It would also follow Spatie's guidelines:

https://spatie.be/guidelines/laravel-php#translations

**Before/After code snippets**

Before;
`@lang('messages.welcome')`
After:
`{{ __('messages.welcome') }}`

**Comment by jasonmccreary** [comment]
Absolutely! Great suggestion and links. We'll get this into the next patch release as part of the "Blade Directives" task.

**Comment by jasonmccreary** [comment]
This has been updated in the latest release (0.4.2). Let us know if you still see the issue.

**Comment by ordago** [comment]
Awesome! It worked perfectly. Sorry for making so many issues.

**Comment by jasonmccreary** [comment]
@ordago no worries. We're still considering this an _alpha_ version. So I'm glad you're finding them. Hopefully you're still getting some good value out of the app.
