### ISSUE TITLE
Bump Laravel Dependencies should take into account the project

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#18]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.4.0.0

**Describe the bug**
```
    "require": {
        "php": "7.4.18",
```
I have not yet upgraded to php 8 and the task Bump Laravel Dependencies upgraded spatie's laravel-activitylog from version 3 to version 4 where they removed support for php7.

https://github.com/spatie/laravel-activitylog/releases/tag/4.0.0

**To Reproduce**
1. Run Bump Laravel Dependencies task

**Comment by jasonmccreary** [comment]
We are working on a feature to allow users to specify the PHP version within the environment Shift uses. May be a few weeks. Until then, we'll look into trying to honor the PHP version if specifically set within `composer.json` for this task.

**Comment by jasonmccreary** [comment]
This should be resolved in the latest release (0.5.2). There may be more packages to manage, but the core packages should be honored.
