### ISSUE TITLE
Licence Activation not working

### ISSUE THREAD

**Issue by anugupta** [laravel-shift/workbench-issues#2]
**Desktop:**
 - OS: MacOS
 - OS Version: Big Sur 11.4
 - App Version: 0.2.0

**Describe the bug**
Licence Activation doesn't work - button stays at 'activating...' and doesn't change. The application hasn't crashed, can still access menus, and they all work, but the licence key modal doesn't go away. Quitting ad restarting app shows app still unlicenced. 

**To Reproduce**
1. WorkBench > Licence Key
2. Enter licence key
3. Click activate

**Comment by jasonmccreary** [comment]
@jessarcher can you take a look at this? I'm not seeing anything on the server-side, so I'd like to determine where it might be client side.

**Comment by jasonmccreary** [comment]
@anugupta, if you want to email support (shift@laravelshift.com), we can take a closer look as this doesn't seem to be wide-spread.

**Comment by jasonmccreary** [comment]
@anugupta, we've pushed a patch release (0.2.1) which should resolve this issue. You should be prompted to update next time you open the app. After which, you may try activating your license key again.
