### ISSUE TITLE
Prefill OS, OS Version and App version in bug report

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#20]
Absolutely not needed, but it would be cool.

**What would you like to do?**
In the spirit of automation, if Workbench knows those params (OS, OS Version and App version) it could prefill them on the link to the GitHub issue.

I tried and it seems the body can be passed through the get param just like with `mailto:`

`&body=issue_body_here`

![image](https://user-images.githubusercontent.com/6376814/125496625-f3fc360e-5e4b-44d5-a4fa-267f109b7af2.png)

**Before/After code snippets**

```diff
-      - OS: [e.g. Mac, Windows, Linux]
+      - OS: Windows
-      - OS Version: [e.g. Big Sur, 10, 18.12]
+      - OS Version: 10
-       - App Version: [e.g. 0.1.0]
+       - App Version: 0.4.0.0

**Comment by jasonmccreary** [comment]
Interesting. Nice touch.

**Comment by jasonmccreary** [comment]
Doesn't look like there is a way to pass in variables to a GitHub template. Going to close this.
