### ISSUE TITLE
Adopt anonymous migrations adds extra semicolon when rerun

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#22]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.4.0.0

**Describe the bug**
I added a migration with [Laracast Generators](https://github.com/laracasts/Laravel-5-Generators-Extended#pivot-tables) and I noticed it didn't use the stubs so I ran the task again. The diff is showing an extra semicolon in every migration. Ideally they shouldn't be affected if they're already anonymous.

**To Reproduce**
1. Run task

![phpstorm64_ywaq3ElfxW](https://user-images.githubusercontent.com/6376814/125684386-c43b5d29-c52d-48a0-8dce-8bc2618ceaf2.png)

**Comment by jasonmccreary** [comment]
Good catch. We'll get this patched up.

**Comment by jasonmccreary** [comment]
This should be resolved in the latest update (0.4.3).
