### ISSUE TITLE
WSL path to project recognised but won't run check - "Failed to find artisan"

### ISSUE THREAD

**Issue by colinmackinlay** [laravel-shift/workbench-issues#23]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version:0.4.2.0

**Describe the bug**
My project is stored in WSL so the path to the project can be either `Z:\home\colin\project` or `\\wsl$\home\colin\project` when I browse in Windows Explorer. Only the mapped drive version is recognised as a valid project path in Workbench. When I run a check the docker image spawns fine but at the preparing build step I get the error
```
Analyzing project...
Failed to find artisan
``` 
I

**To Reproduce**
Steps to reproduce the behaviour:
1. Create Laravel project in WSL
2. Run Workbench
3. Set project path
4. Run a check

![image](https://user-images.githubusercontent.com/7833362/125694819-f1f8e4f3-151d-42b5-9391-d03d77e50c6f.png)

**Comment by jasonmccreary** [comment]
We don't have access to a Windows machine with WSL storage. So it will not be possible for us to recreate this issue.

A few clarifications:

- What path are you entering?
- Is `artisan` underneath that path? Is it a direct child or deeper?
- Is Workbench displaying an error when you try to select the WSL path?

**Comment by colinmackinlay** [comment]
Hello Jason – impressive response time 😊

  1.  The path I am entering is as per the issue: \\wsl$\home\colin\project which isn’t recognised by workbench. I also have \\wsl$<file://wsl$> mapped as a drive to Z:\ so I can also use the path Z:\home\colin\project workbench recognises this but then throws the error
  2.  Artisan is a direct child there – the standard Laravel project setup
  3.  Yes – if I use wsl$ directly I get this error

***@***.***D77903.8EFBD310]

If I use Workbench to analyse a project stored in the native windows filesystem say at C:\Users\Colin\Project then it runs absolutely fine

Guess it’s going to be quite tricky to track down. I’m sure I can play with it in a github repository for now. Reviewing changes locally and testing locally would have been preferable but I know that WSL does present some UNC path challenges to some software. PhpStorm was the reverse, it couldn’t cope with mapped network drives for runtime configurations but is fine with the \\wsl$<file://wsl$> access!

**Comment by jasonmccreary** [comment]
Looks like part of your reply got encoded. So I'm not sure the error message.

Anyway, we'll do some research and see if we find any open issues or notes related to mapping WSL paths in Electron.

**Comment by colinmackinlay** [comment]
Thanks. In case it helps the error is this:
![image](https://user-images.githubusercontent.com/7833362/125748448-484fe12e-5c6c-403c-9b45-508948930473.png)

**Comment by jasonmccreary** [comment]
@colinmackinlay, out of curiosity, which task were you trying to run?

**Comment by colinmackinlay** [comment]
`Short array syntax` - just the first one in the list as a test. Just tried `Use ::class constant` and had same issue @jasonmccreary

**Comment by svpernova09** [comment]
@colinmackinlay Hi! I've been running Workbench in WSL2. A couple of questions to help debug:

Are you using WSL 1 or WSL 2? (To check run `wsl -l -v` in Powershell and look for your Distribution name and the corresponding version)

How are you running Docker? Are you using Docker Desktop's WSL2 based engine?

Assuming you're running WSL2 + Docker's WSL2 engine: IMHO You shouldn't run the Workbench app *from Linux* on your `/mnt/c/` mapped files. I also would avoid running the Windows app on `\\wsl$\` mounted files but this is probably ok (just slow because you're crossing the virtualization across filesystems and I'm heavily biased towards doing everything in WSL2).

I'm running the Linux native Workbench app installed inside my Ubuntu 20.04 WSL2 Distro using Docker Desktop + WSL2 engine against projects that live *inside* my WSL2 filesystem at `/home/username/Code`

**Comment by colinmackinlay** [comment]
@svpernova09 Hello Joe - WSL2 is running
![image](https://user-images.githubusercontent.com/7833362/126221951-ddabcb94-b1c1-47f2-a8d7-491b5c5c2e97.png)

I'm running Workbench from Windows but the files are all in linux on `\\wsl$\` 

For projects on `c:\` Workbench (from Windows) is fine

I suppose I could run Workbench from linux but I guess I'd need to add a desktop environment on linux for that which seems like overkill!

**Comment by svpernova09** [comment]
Using Version 0.4.5 of Workbench on Windows 10; I'm unable to reproduce the original bug where the Workbench app can't find the path. Running the php/code-format against a Laravel 8 project stored on the WSL2 path `\\wsl$\jameson\home\halo\Code\rfid` completed successfully and as expected.

Browsing from Local project to WSL path:

![image](https://user-images.githubusercontent.com/967362/126228939-38475f6b-b6a4-408d-97e7-d52b1002ff59.png)


Completed successfully:

![image](https://user-images.githubusercontent.com/967362/126228643-5a11bedb-fd2c-469c-9ff6-ca608684bb13.png)


Expected `git status` changes:

![image](https://user-images.githubusercontent.com/967362/126228719-741ab757-c4ac-4a0a-ac39-f9c2a338c412.png)

I also ran a few other tasks in this fashion and they all completed as expected.

It's possible you're not using the WSL2 Docker Desktop engine. I would double-check this as I've seen updates break distros. Docker Desktop -> Settings Make sure "Use the WSL 2 based engine" is checked:

![image](https://user-images.githubusercontent.com/967362/126229283-f73046d7-de66-40bd-9512-028d122fb4ac.png)

Then go into Resources -> WSL Integration and make sure your default distro is selected (and is correctly set to what you expect it to be) or you can individually enable docker per distro. Here's my configuration showing my primary "jameson" distro:

![image](https://user-images.githubusercontent.com/967362/126229442-49f3f9cd-7ce4-43d5-b1c8-91e297304c0c.png)

**Comment by colinmackinlay** [comment]
@svpernova09 thanks Jason! WSL2 engine was enabled but integration with additional distros wasn't. That didn't work but then a combination of upgrading Workbench, rebooting and then also removing the network drive mapping has cleared it and I've run some inspections successfully.

@jasonmccreary thank you for investigating too :)

**Comment by svpernova09** [comment]
Glad you got it working!

--
- Joe Ferguson
JoeFerguson.me
osmihelp.org

**Comment by jasonmccreary** [comment]
@colinmackinlay, glad you got it working. All thanks goes to @svpernova09 for stepping in and sharing his knowledge. I had suspected it was a local configuration issue based on the actual filesystem reporting "path not found". But had no idea where to look.

**Comment by colinmackinlay** [comment]
@svpernova09 Hi Joe, have you found a permissions issue with your config? Now that I've got this working, Workbench works fine with files in my projects but changes their ownership from colin:colin to root:root

I then have to `sudo chown- R colin:colin proect` before I can carry on editing manually with my IDE (PhpStorm)

**Comment by jasonmccreary** [comment]
@colinmackinlay, this is a known issue. We're looking into it and will push a patch soon.
