### ISSUE TITLE
Common docker issues

### ISSUE THREAD

**Issue by amaelftah** [laravel-shift/workbench-issues#24]
**What would you like to do?**
after I installed docker on ubuntu machine .... i found workbench still giving this error 

![Screenshot from 2021-07-15 13-20-28](https://user-images.githubusercontent.com/17250137/125784754-74688e47-4377-4e9f-a09a-99f531c622a5.png)

after I spend an hour or two search,ing I found [this article solved my problem](https://dev.to/try_catch/docker-connect-permission-denied-solved-1d2g)

i know that docker issues will be different from one machine to another .... but I would suggest something like common docker issues with links to solve them ... or if possible a short youtube video of quick start guide with docker and some common issues that can happen

**Comment by jasonmccreary** [comment]
Thanks for reporting. This does appear to be part of the [post install instructions](https://docs.docker.com/engine/install/linux-postinstall/).

However, we will keep this in mind for a future FAQ or troubleshooting section as you suggested.
