### ISSUE TITLE
Ability to stop long running task

### ISSUE THREAD

**Issue by amaelftah** [laravel-shift/workbench-issues#25]
**What would you like to do?**
sometimes I run task that may take long time or I some times I run task by mistake on different project ... so I think the ability to stop a task that would be awsome

**Comment by jasonmccreary** [comment]
Great idea. We'll look into adding this in a future release.

In the meantime, you can look under the "Analyzing project" section to see if you have a "large project" and tips for possibly speeding up some of tasks. Specifically the PHP ones.

**Comment by jasonmccreary** [comment]
This has been added in v1.0.0. You may selected _Kill_ from the build menu or via a keyboard shortcut (Ctrl + Alt + K or Cmd + Opt + K)
