### ISSUE TITLE
Workbench grouped tasks

### ISSUE THREAD

**Issue by amaelftah** [laravel-shift/workbench-issues#26]
**What would you like to do?**
sometimes I want to run multiple tasks together on different projects so my suggestion is :

- have yaml file same as web interface ... to run multiple tasks after each other

- ability to save those tasks under a certain name in order to run them on different projects

**Comment by jasonmccreary** [comment]
This exists!

- Switch to "Editor Mode" (from the _Build_ menu or Ctrl + Shift + E)
- Add the tasks you wish to run to the editor
- Save the build as YAML (from the _File_ menu or Ctrl + S)

When you want to use it on another project in the future (or share it), simply open the build YAML (from the _File_ menu or Ctrl + O) and the app will automatically switch to "Editor Mode" and load your tasks.

**Comment by amaelftah** [comment]
sorry my mistake didn't see it

**Comment by jasonmccreary** [comment]
No worries. Lots of features inside the Workbench.
