### ISSUE TITLE
Adopt anonymous migrations deleted the content of the stubs

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#27]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.4.4.0

**Describe the bug**
The stubs were created when I previously ran the task. After running it again to convert a new migration it has emptied the content of the stubs.

**To Reproduce**
Steps to reproduce the behaviour:
1.  Run Task

I added the return type to the stubs. That might have caused the issue.

![image](https://user-images.githubusercontent.com/6376814/125932777-ade35a1f-0993-4d49-9e08-d7b31f01e84d.png)

![image](https://user-images.githubusercontent.com/6376814/125932954-deebacd4-154d-4114-90c9-04dfc0160eca.png)

**Comment by jasonmccreary** [comment]
This is a bug introduced in the last release. We'll get a patch out later today.

**Comment by jasonmccreary** [comment]
This should be resolved in the latest release (0.4.5).
