### ISSUE TITLE
"Failed to run rector" on a few tasks

### ISSUE THREAD

**Issue by adrianspacely** [laravel-shift/workbench-issues#28]
**Desktop:**
 - OS: Mac
 - OS Version: 11.4
 - App Version: 0.4.4

**Describe the bug**

I've been running a few simple refactoring tasks to dip my toes in, but have been receiving this error:

```
Running: php/null-coalesce
7s
>>> Event: Processing paths: app, database/factories, database/seeders, config, database/migrations, routes, tests
Fatal error: Class PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (PHPStan\PhpDocParser\Ast\Node::setAttribute, PHPStan\PhpDocParser\Ast\Node::hasAttribute, PHPStan\PhpDocParser\Ast\Node::getAttribute) in /project/vendor/phpstan/phpdoc-parser/src/Ast/Type/IdentifierTypeNode.php on line 5
Failed to run rector: adopt-null-coalesce: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/AdoptNullCoalesce.php(18): Shift\Tasks\Workbench\AdoptNullCoalesce->rector('/opt/shift/reso...')
#1 phar:///opt/shift/workbench/workbench.php(91): Shift\Tasks\Workbench\AdoptNullCoalesce->perform()
#2 /opt/shift/workbench(9): require('phar:///opt/shi...')
#3 {main}
```

At first, I thought it was to do with my project's dependencies, but my project's `PHPStan\PhpDocParser\Ast\Type\IdentifierTypeNode` had no abstract methods.

I experienced this issue on the following tasks:

* Convert create_function
* Null Coalesce
* Array Destructuring

Stopped running tasks after that assuming this would likely come up a few more times.

**Comment by jasonmccreary** [comment]
@adrianb93, we normally see this issue when there is a local dependency conflicting. Can you try some of the potential work arounds listed in #13, particularly removing your dev dependencies, and see if it resolves this issue.

**Comment by jasonmccreary** [comment]
@adrianb93 did removing your development dependencies help?

**Comment by adrianspacely** [comment]
Hey, I haven't forgotten about this. I will be trying those suggestions later this week 🙂

**Comment by adrianspacely** [comment]
I followed the steps. Got a different error this time, not enough info to debug with:

```
Running: php/array-destructuring
>>> Event: Processing paths: app, database/factories, database/seeders, config, database/migrations, routes, tests
Failed to run rector: adopt-array-destructuring: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/AdoptArrayDestructuring.php(18): Shift\Tasks\Workbench\AdoptArrayDestructuring->rector('/opt/shift/reso...')
#1 phar:///opt/shift/workbench/workbench.php(91): Shift\Tasks\Workbench\AdoptArrayDestructuring->perform()
#2 /opt/shift/workbench(9): require('phar:///opt/shi...')
#3 {main}
{"event":"step-failed","data":{"step":"phparray-destructuring","runtime":"98.562967"}}
```

If it's relevant, our project is still on PHP 7.4

**Comment by jasonmccreary** [comment]
It's possible there may be a 7.4 to 8.0 difference in the code causing it to fail. But unlikely.

If you have a moment, maybe you could try running this in the [cloud-based Workbench](https://laravelshift.com/workbench). That would let us know it's a local issue and not a project/code issue.

**Comment by jasonmccreary** [comment]
Closing as unanswered.
