### ISSUE TITLE
Property Promotion not working

### ISSUE THREAD

**Issue by anugupta** [laravel-shift/workbench-issues#3]
**Desktop:**
 - OS: MacOS
 - OS Version: Big Sur
 - App Version: 0.2.0

**Describe the bug**
Property promotion fails with `Failed to run rector: adopt-property-promotion: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/AdoptPropertyPromotion.php(18):`

**To Reproduce**
1. run property promotion task
<img width="1008" alt="screenshot2021-06-30 at 22 49 10@2x" src="https://user-images.githubusercontent.com/105964/124036120-6b93df00-d9f5-11eb-9eeb-89ff12f313f5.png">

**Comment by jasonmccreary** [comment]
@anugupta, would it be possible for you to attempt to run this on the [cloud-based Workbench](https://laravelshift.com/workbench). This would help me determine if something within your specific project is failing or within our underlying Docker build.

**Comment by anugupta** [comment]
@jasonmccreary – I tried it on the cloud version, and it completed and created a PR.

However, the PR was empty apart from a placeholder readme, and I was expecting 1 change (if I understand property promotion correctly).

This was the code I was expecting to be changed:

``` php
class ParserService
{
    protected Collection $tags;
    protected Collection|null $bannedTerms = null;
    protected MultiStringMatcher $searchTermsMatcher;
    protected MultiStringMatcher|null $bannedTermsMatcher = null;

    public function __construct( Collection $tags, Collection $bannedTerms = null )
    {
        $this->searchTermsMatcher = new MultiStringMatcher( $tags->keys()->toArray() );

        if ( $bannedTerms?->isNotEmpty() ) {
            $this->bannedTermsMatcher = new MultiStringMatcher( $bannedTerms->toArray() );
        }

        $this->tags        = $tags;
        $this->bannedTerms = $bannedTerms;
    }
```

This might be a separate issue (or a non-issue).

**Comment by jasonmccreary** [comment]
Maybe. I'd like to take a closer look though. What was your build number from the cloud-based run? (it will be the suffix of the branch name)

**Comment by anugupta** [comment]
> Maybe. I'd like to take a closer look though. What was your build number from the cloud-based run? (it will be the suffix of the branch name)

Build number: 1602

**Comment by jasonmccreary** [comment]
@anugupta, looks like this is indeed missed by Rector. I think there are a few things which confuse it.

- The mixed type for `$bannedTerms`
- The default value for `$bannedTerms`
- The additional logic within the constructor

So, although this snippet could likely be collapsed with some property promotion, it appears Rector shies away from it.

I am going to close this issue here and instead open an issue/PR for Rector to improve this for everyone.

In the meantime, this is probably how I'd expect the refactored code to look:

```php
    protected MultiStringMatcher $searchTermsMatcher;
    protected ?MultiStringMatcher $bannedTermsMatcher = null;

    public function __construct( protected Collection $tags, protected ?Collection $bannedTerms = null )
    {
        $this->searchTermsMatcher = new MultiStringMatcher( $tags->keys()->toArray() );

        if ( $bannedTerms?->isNotEmpty() ) {
            $this->bannedTermsMatcher = new MultiStringMatcher( $bannedTerms->toArray() );
        }
    }
```

Again, not sure if that is even valid. Let me know if you end up trying it.
