### ISSUE TITLE
Allow running tasks as non-root user

### ISSUE THREAD

**Issue by mortenscheel** [laravel-shift/workbench-issues#30]
**What would you like to do?**
When I run Workbench locally, the modified files end up being owned by root. It would be great if I could choose a different user:group to run the tasks as. Or if Workbench could just leave the ownership unchanged, that would be even better.

I'm running Workbench in Ubuntu 20.04 (through WSL2 on Windows 10)

**Comment by jessarcher** [comment]
Hey @mortenscheel, thanks for the feedback! I've actually been working on this already as I'm also on Linux and have the same issue. We just need to make sure the changes don't break Mac or Windows and then we'll release it :+1:

**Comment by jasonmccreary** [comment]
@mortenscheel, this should be patched in the latest release (0.4.7). Let us know if you have any issues.
