### ISSUE TITLE
Not running in windows

### ISSUE THREAD

**Issue by mateusgalasso** [laravel-shift/workbench-issues#31]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: [e.g. 0.1.0]

**Describe the bug**
Spawned Docker background process with PID 10628
docker: Error response from daemon: error while creating mount source path '/run/desktop/mnt/host/c/Users/mateu/AppData/Roaming/Workbench/build.json': mkdir /run/desktop/mnt/host/c: file exists.

**To Reproduce**
1 - select any task
2 - run 

![image](https://user-images.githubusercontent.com/3990028/127344128-d74e71fe-3886-4d12-9720-c202a90f941b.png)

**Comment by jasonmccreary** [comment]
The Workbench certainly works on Windows. This is likely a path or Docker issue.

Can you review the comment for #23 and see if that has any tips which may help.

**Comment by mateusgalasso** [comment]
You were right!!! I erased some volumes and  it's working now. 
Thks.

**Comment by jasonmccreary** [comment]
@stonkeep, awesome. Glad you got it.
