### ISSUE TITLE
PHP tags in blade files

### ISSUE THREAD

**Issue by roylaveto** [laravel-shift/workbench-issues#32]
**Desktop:**
 - OS: Mac
 - OS Version: Big Sur
 - App Version: 0.4.7

**Describe the bug**
When running some tasks it adds PHP tags to blade files. It sees these as actual problems fixed, whilst it messes up the files.

**To Reproduce**
1. Have a Laravel project with blade files
2. Run php/create_function
3. Check changes

https://imgur.com/a/Yxq4agt

**Comment by jasonmccreary** [comment]
I actually noticed this myself yesterday when using the new _Format_ tests task.

We'll take a closer look and get this fixed.

**Comment by Roy-Ernst** [comment]
Great to hear that it's getting fixed!

I noticed something else, the normal fixes run just fine. But the 'Laravel' fixes finish within 1 second and don't show any output. Maybe it's just me but it doesn't seem to be working no matter what I do.

https://imgur.com/a/ReSCpc1

**Comment by jasonmccreary** [comment]
@Roy-Ernst, please open a separate issue for other bugs. Otherwise, it'll get lost in the thread. 👍

**Comment by jasonmccreary** [comment]
@Roy-Ernst this unfortunately looks like a bug introduced by Rector - which is a tool some of these PHP tasks use underneath. @jessarcher has [reported this bug](https://github.com/rectorphp/rector/issues/6622) to them, so hopefully we'll see a fix soon.

In the meantime, I think there's more value in receiving the changes and removing any added PHP tags than ignoring Blade templates entirely.

**Comment by jessarcher** [comment]
This has now been fixed upstream. Just need to wait for a rector release and then we can release a Workbench update.

**Comment by jasonmccreary** [comment]
This should be resolved in the latest release (0.5.2). Let us know if you still see a problem.
