### ISSUE TITLE
Convert optional helper to php8 ?->

### ISSUE THREAD

**Issue by SudoGetBeer** [laravel-shift/workbench-issues#35]
Hello,
thanks for the great tool!

**What would you like to do?**
Would be nice to convert all optional($var)->name to $var?->name (for PHP8).

**Before/After code snippets**
Before:
```php
optional(optional(optional($products->get($i))->manufacturer)->address)->street
```
After:
```php
$products->get($i)?->manufacturer?->address?->street
```

Best regards

**Comment by jasonmccreary** [comment]
@SudoGetBeer, I like it. @freekmurze asked for this as well. So we'll build it in either as a separate tool or the "Null safe" task.

**Comment by jasonmccreary** [comment]
This has been added in 0.6.0 as the "optional to nullsafe" task. There are some complex snippets (like the nested on you have) it may not yet convert. But should get most. We'll continue to tweak it. 👍
