### ISSUE TITLE
Convert 'magic' accessors or mutators in to traditional methods

### ISSUE THREAD

**Issue by patrick-radius** [laravel-shift/workbench-issues#37]
As mentioned on Twitter we have projects where devs have in the past make extreme uses of accessors and mutators.
So for example a User class has something like:
```php
public function getContactsAttribute()
    {
        $users = Cache::remember(
            'user-contacts-' . $this->id,
            240,
            function () {
                return User::NetworkUsers($this->id)
                           ->havingPermissions([MenuPermissions::conversations(true)])
                           ->orderBy('firstname')
                           ->get();
            }
        );

        return $users;
    }
 ```
which is then used all over the codebase as `$user->contacts`

For simple stuff like concatenating firstname and lastname into a fullname property i think accessors are great.
But i think this example shows there's way too much code/logic in it. This is hardly a property anymore.

Now if there was full support for it in IDE's there wouldn't be much issue to refactor it by hand, but this is not the case.
Laravel ide-helper does add property decorations for these properties, but when a model using this is passed to a blade view for example the knowledge about these properties is lost.
 

given the previous example code snippet, i'd be happy if workbench could at least generate normal corresponding methods.

```php
public function getContacts()
    {
        $users = Cache::remember(
            'user-contacts-' . $this->id,
            240,
            function () {
                return User::NetworkUsers($this->id)
                           ->havingPermissions([MenuPermissions::conversations(true)])
                           ->orderBy('firstname')
                           ->get();
            }
        );

        return $users;
    }
 ```

And maybe also modify the original accessor as:
```php
public function getContactsAttribute()
{
   return $this->getContacts();
}
```
for backwards compatibility.

But ofcourse it would be even more fantastic if it could detect all the uses of the original accessor property and change to use the new methods directly.

**Comment by jasonmccreary** [comment]
@patrick-radius, I think this is a cool bit of automation. Especially for a legacy code base. I could see it having a few options as well. So I'd like to think through those over the next few weeks. Maybe see what I'd want converted in my own code.

In the meantime, if you have more snippets, feel free to comment with more code.

**Comment by jasonmccreary** [comment]
@patrick-radius, do you think the new single accessor/mutator method (#67) is an acceptable middle ground for this? Or would you still want something to alias these Laravel convention methods?

**Comment by patrick-radius** [comment]
Thanks so much for still having this in mind.
I think the new accessor/mutator syntax is an improvement, however I still think it's hard to find usages of the 'magic' properties in a larger project.
I'm curious how other teams deal with this.

There's of course the possibility to add `@Property` docblocks, but I'd still prefer the possibility to convert the magic properties to normal method calls.

**Comment by jasonmccreary** [comment]
Ok, I'll keep this on the list. But looking at it more, the implementation would probably be to delegate to the Laravel accessor/mutator. This is less of a code change and preserves the Laravel convention.

For example:

```php
public function getContacts()
{
   return $this->getContactsAttribute();
}
```

**Comment by jasonmccreary** [comment]
After additional review, I don't think this is something we'll add. Seems too specific and doesn't really align with Laravel conventions.
