### ISSUE TITLE
Build failed with missing shiftrc dotfile during "Bump Laravel Package Dependencies"

### ISSUE THREAD

**Issue by mberneis** [laravel-shift/workbench-issues#39]
**Desktop:**
 - OS: Mac OSX
 - OS Version: 11.5.2
 - App Version: 0.5.2

**Describe the bug**
Running "Bump Laravel Package Dependencies" with Append YES and Version 8.0 on my application
Getting notice about missing `.shiftrc` - Not sure if I am supposed to provide this in my code or if generated (and failed) by docker process.

![image](https://user-images.githubusercontent.com/30384/132425342-533a8966-667c-4b4e-8a81-ed02cbf070d1.png)

**Comment by jasonmccreary** [comment]
Is your project a Laravel package or a Laravel application?

**Comment by mberneis** [comment]
An application

**Comment by jasonmccreary** [comment]
While it may not fix the problem, this particular task is for Laravel Packages, not Laravel applications. We are tweaking the task description in the next release.

Please try the "Bump Laravel Dependencies" task instead and let me know if that works.

**Comment by mberneis** [comment]
That works - thank you! - I misunderstood the task - thought it would look into non-laravel packages and upgrade those dependencies used in the application

**Comment by jasonmccreary** [comment]
Excellent. That wording will be cleaned up in the next release.
