### ISSUE TITLE
Minor: "Streamline order methods" PHP warning

### ISSUE THREAD

**Issue by BrandonSurowiec** [laravel-shift/workbench-issues#40]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.5.2

**Describe the bug**
In the output log of the "Streamline Order by task" there was this PHP warning:

```php
Warning: Undefined property: PhpParser\Node\Expr\BinaryOp\Concat::$name in phar:///opt/shift/workbench/src/Parsers/Finders/QueryOrderByFinder.php on line 23
```

The task still works perfectly in converting a bunch of `orderBy` statements. 

**To Reproduce**
1. Run 'Streamline order methods' task using Desktop Workbench

![image](https://user-images.githubusercontent.com/5625680/132509771-a3434f79-8148-4cd3-911a-a4d9f69646c8.png)

**Comment by jasonmccreary** [comment]
Some tasks will emit raw warnings for syntax they don't expect. While not the best UX from our side, it's proven better than to silence them.

I'll keep it in mind if it pops up again, but I'm going to close this for now.

**Comment by BrandonSurowiec** [comment]
No problem! Was unsure whether it meant my code was doing something unruly or if there was a possible edge-case that couldn't be converted. If the former, would be cool to know what file and line, but I digress. Thanks for all your work over the years to make our jobs easier!

**Comment by jasonmccreary** [comment]
Totally agree. This could be cleaner for sure. I'll keep it in mind.
