### ISSUE TITLE
laravel/tuple-action also runs laravel/fluent-routes

### ISSUE THREAD

**Issue by mortenscheel** [laravel-shift/workbench-issues#42]
**Desktop:**
 - OS: Ubuntu
 - OS Version: 20.04
 - App Version: 0.5.2

**Describe the bug**
Running the laravel/tuple-action shift also runs laravel/fluent-routes.
This is unexpected, since it isn't mentioned in the task description.

Workaround: Running laravel/class-based-routes will also run tuple-action, but not fluent-routes.

**To Reproduce**
Run laravel/tuple-action on a project containing the routes defined with array syntax.

**Comment by jasonmccreary** [comment]
In Laravel 8, you can not use the options array-syntax with tuple actions. So while implicit, it is a requirement of using "tuple actions".

**Comment by mortenscheel** [comment]
@jasonmccreary I think we misunderstand each other. Laravel 8 has no problem with tuple-action routes inside a Route group with options array.

I expect `laravel/tuple-action` to turn this
```php
Route::group(['prefix' => 'users', 'as' => 'users.', 'middleware' => 'auth'], function() {
    Route::get('/', 'App\Http\Controllers\UserController@index')->name('index');
    // More routes...
});
```
Into this (which works fine in Laravel 8):
```php
Route::group(['prefix' => 'users', 'as' => 'users.', 'middleware' => 'auth'], function() {
    Route::get('/', [UserController::class, 'index'])->name('index');
    // More routes...
});
```
But I get this, where the route group is also transformed to fluent syntax:
```php
Route::prefix('users')->name('users.')->group(function() {
    Route::get('/', [UserController::class, 'index'])->name('index');
    // More routes...
});
```

In other words, I expected tuple-action to ignore the route groups and just turn `Controller@action` into `[Controller::class,  'action']`... which is *exactly* what happens when running `laravel/class-based-routes`.

**Comment by jasonmccreary** [comment]
I see now. Thanks. I will reopen this to run a "minimal" version of converting to fluent routes when the "tuple syntax" task is run.

**Comment by jasonmccreary** [comment]
Given the direction of Laravel 9 continuing to adopt fluent routes and now add additional grouping methods like `Route::controller`, I'm closing this as I feel it could create confusion when Shift did not convert certain "outdated" conventions.
