### ISSUE TITLE
nullsafe-operator only changing first one

### ISSUE THREAD

**Issue by ricklambrechts** [laravel-shift/workbench-issues#43]
**Desktop:**
 - OS: Windows 10
 - OS Version: 20H2
 - App Version: 0.5.2

**Describe the bug**
The nullsafe-operator task only changes the first sentence inside an if statement.

**To Reproduce**
1. I have this code:
```
if ($this->variable !== null) {
    $this->something = $this->variable->name;
    $this->something2 = $this->variable->first_name;
    $this->something3 = $this->variable->last_name;
    $this->something4 = $this->variable->phone_number;
}
```
2. I run nullsafe-operator.
3. Then i have this code:
```
$this->something = $this->variable?->name;
```
4. Expected to have:
```
$this->something = $this->variable?->name;
$this->something2 = $this->variable?->first_name;
$this->something3 = $this->variable?->last_name;
$this->something4 = $this->variable?->phone_number;
```

**Comment by jasonmccreary** [comment]
@jessarcher, can you take a look at this? I feel I too have seen where Rector only picks up the first change.

**Comment by jasonmccreary** [comment]
We have decided these free tasks backed by Rector are not something we will support. You are welcome to try and run this via Rector directly. If that fails, you should [open a Rector issue](https://github.com/rectorphp/rector/issues).

Alternatively, you may try running the [cloud-based Workbench](https://laravelshift.com/workbench) to rule out any local dependency issues. If that succeeds, you may have a local file or dependency which conflicts with Rector.
