### ISSUE TITLE
Duplicate namespace path in tuple action

### ISSUE THREAD

**Issue by eby** [laravel-shift/workbench-issues#44]
**Desktop:**
 - OS: Mac
 - OS Version: 12 beta
 - App Version: 0.5.2

**Describe the bug**

When running actions to tuples (tuple-action) on a file that has the full class path in action() it appends a duplicate namespace in front. This code is probably not really great to begin with but it does work.

**To Reproduce**

1. Have a file that contains code like: `action('App\Http\Controllers\FooController@function')`
2. Run the actions to tuples job
3. Code generated is `action([\App\Http\Controllers\App\Http\Controllers\FooController::class, 'function']`

**Comment by jasonmccreary** [comment]
@eby, just to snag a bit more context, is you Laravel app namespace `App`, or have you customized it?

**Comment by eby** [comment]
Yes, all default namespaces. Controllers are `namespace App\Http\Controllers;`

**Comment by jasonmccreary** [comment]
Awesome. Okay, we'll get this fixed up.

**Comment by jasonmccreary** [comment]
@jessarcher, we should probably check if the top-level namespace matches a known _app namespace_. If so, skip prefixing the controller namespace.

**Comment by jasonmccreary** [comment]
This should be patched in the latest release (0.6.1). Let us know if not.
