### ISSUE TITLE
New task: Change usages of FakerPHP property accessors to method calls

### ISSUE THREAD

**Issue by ordago** [laravel-shift/workbench-issues#47]
**What would you like to do?**

https://github.com/FakerPHP/Faker/pull/164

In that pull request FakerPHP has marked property access as deprecated

```php
    /**
     * @param string $attribute
     *
     * @deprecated Use a method instead.
     */
    public function __get($attribute)
    {
        trigger_deprecation('fakerphp/faker', '1.14', 'Accessing property "%s" is deprecated, use "%s()" instead.', $attribute, $attribute);


        return $this->format($attribute);
    }
```

**Before/After code snippets**

```diff
- $this->faker->lastName;
+ $this->faker->lastName();
```

**Comment by jasonmccreary** [comment]
@jessarcher, this could be a cool PHP task.

**Comment by jessarcher** [comment]
This is a great idea!

**Comment by jasonmccreary** [comment]
Sorry for the delay here. This was added a little while back as the _Faker methods_ task.

**Comment by ordago** [comment]
@jasonmccreary 👍 saw it on the changelog at the time.
