### ISSUE TITLE
composer/laravel-package-dependencies duplicates constrains

### ISSUE THREAD

**Issue by tobz-nz** [laravel-shift/workbench-issues#5]
**Desktop:**
 - OS: [e.g. Intel Mac
 - OS Version: Big Sur,
 - App Version: 0.2.1

**Describe the bug**
composer/laravel-package-dependencies duplicates some constrains. 
E.g.:
```
"nunomaduro/collision": "^5.0|^5.0",
```

**To Reproduce**
just running the task should be enough.

**Comment by jessarcher** [comment]
Thanks for reporting this @tobz-nz! I'm looking at it now.

**Comment by jasonmccreary** [comment]
This should be fixed in release 0.2.2 thanks to @jessarcher. You should be prompted next time you open the Workbench to update.
