### ISSUE TITLE
Format Test Cases incorrectly formatting "setUp" method

### ISSUE THREAD

**Issue by shawnveltman** [laravel-shift/workbench-issues#50]
**Desktop:**
Mac
Montery 
12.0.1

**Describe the bug**
When running the Format Test Cases task, and selecting the "annotation" method, I expect it to only add annotations that don't exist IF the method is prefixed by test. The behavior of the task instead seems to add the annotation to all methods (most noticeably, the setUp method)

**To Reproduce**
1. Have a test suite with a setUp method
2. Run the Format Test Case task
3. Notice that the setUp method now has a test annotation, when it really shouldn't

<img width="675" alt="Screen Shot 2021-12-01 at 6 24 46 PM" src="https://user-images.githubusercontent.com/8326484/144340736-e1e7f0e6-252c-41d5-825e-cb12923cee03.png">
<img width="607" alt="Screen Shot 2021-12-01 at 6 24 56 PM" src="https://user-images.githubusercontent.com/8326484/144340748-bb90d045-75cc-41b3-b081-b90f022c5452.png">

<img width="695" alt="Screen Shot 2021-12-01 at 6 25 49 PM" src="https://user-images.githubusercontent.com/8326484/144340754-ded62eaa-115d-4ec4-a61a-30e1291cf61f.png">

**Comment by jasonmccreary** [comment]
Technically the `setUp` method is not `public`. It should be `protected`. I believe higher versions of PHPUnit emit a notice for this.

This visibility change is automated by the recent [Laravel upgrade Shifts](https://laravelshift.com/shifts) as well as the [PHPUnit Shifts](https://laravelshift.com/shifts?category=php). I may also add it as a precondition to this task. Which would prevent this confusion.

However, going to close this.
