### ISSUE TITLE
Factory upgrade gone wrong

### ISSUE THREAD

**Issue by jonneroelofs** [laravel-shift/workbench-issues#53]
**Desktop:**
 - OS: MAC intel
 - OS Version: 12.0.1
 - App Version: 0.7.2

**Describe the bug**
Provide a short description of the bug. Just a sentence or two.
Hi,

Just tried to run my first shift in the workbench and ran into some trouble.

The result after running "Class based factories" was multiple broken (invalid php) files. It seems to have broken on a afterCreatingState call when shifting. I'll attach the before and after file as .txt (otherwise I cannot attach them), so if you rename them you can have a go and see what went wrong. 

**To Reproduce**

[UserFactoryBeforeShiftFactory.txt](https://github.com/laravel-shift/workbench-issues/files/7914366/UserFactoryBeforeShiftFactory.txt)
[UserFactoryAfterShift.txt](https://github.com/laravel-shift/workbench-issues/files/7914367/UserFactoryAfterShift.txt)

[PostFactoryAfterShift.txt](https://github.com/laravel-shift/workbench-issues/files/7914353/PostFactoryAfterShift.txt)
[PostFactoryBeforeShift.txt](https://github.com/laravel-shift/workbench-issues/files/7914356/PostFactoryBeforeShift.txt)

**Comment by jasonmccreary** [comment]
@jonneroelofs, the `afterCreatingState` can be recreated in modern Laravel, there is no exact equivalent. As such, Shift doesn't convert these automatically. This should have been noted in the console output.

There  may still be a  bug here, but  I'm curious if this broke for all factories, or just those with `afterCreatingState`.

**Comment by jonneroelofs** [comment]
I reverted the code but as far as I could tell only the ones with afterCreatingState were problematic. 

I think there is actually an option to rewrite the afterCreatingState to modern Laravel because you can call $this->afterCreating from within another state. The only thing I don't now is what happens if you were to do that from multiple states. 

To be clear, you could rewrite:
```php
$factory->state(User::class, 'admin', function(){
    return ['admin' => true]
})->afterCreatingState(User::class, 'admin', function ($user){
    // do some stuff
})
```

To:
```php
public function admin(){
    $this->afterCreating(function(User $user){
        // do some stufff
    })

    return ['admin' => true]
}
```

**Comment by jonneroelofs** [comment]
Just had a look at the factory source code, looks like it handles multiple callbacks.

![image](https://user-images.githubusercontent.com/20800818/150752779-59b35656-105e-46b7-978d-f758d8c0a956.png)

![image](https://user-images.githubusercontent.com/20800818/150752828-4b7c6a26-4b1e-43be-a46f-abc63518f0c4.png)

**Comment by jasonmccreary** [comment]
We'll take a look to see if these can be converted or at least warned without producing invalid code.

**Comment by jasonmccreary** [comment]
Converting chained callback methods is now supported in release 0.9.0.
