### ISSUE TITLE
Latest && Oldest laravel method

### ISSUE THREAD

**Issue by HAstaShakiba** [laravel-shift/workbench-issues#55]
**What would you like to do?**
Briefly tell us about the problem you'd like to solve.
change orderByDesc and orderBy to latest and oldest method in laravel.

**Before/After code snippets**
If you're suggesting an enhancement or new task, please provide the a before/after code snippet.
`orderByDesc('something') -> latest('something')`

`orderBy('something') -> oldest('something')`

**Comment by jessarcher** [comment]
Great idea! I'll take a look :)

**Comment by jasonmccreary** [comment]
This task was added in `0.8.0`. Let us know when you try it out.

We may eventually add an option to only do this for date/id columns as I would personally I adopt it for those as I find it more readable.
