### ISSUE TITLE
Illuminate\Support\Carbon

### ISSUE THREAD

**Issue by HAstaShakiba** [laravel-shift/workbench-issues#56]
**What would you like to do?**
Briefly tell us about the problem you'd like to solve.

**Before/After code snippets**
If you're suggesting an enhancement or new task, please provide the a before/after code snippet.
`Carbon/Carbon -> Illuminate\Support\Carbon`

**Comment by jasonmccreary** [comment]
I like it, we'll get this task created. 👍

**Comment by jasonmccreary** [comment]
This task was added in `0.8.0`. Let us know when you try it out.
