### ISSUE TITLE
Uncaught TypeError: Unsupported operand types: int + string in phar

### ISSUE THREAD

**Issue by sppet** [laravel-shift/workbench-issues#57]
**Desktop:**
 - OS: mac
 - OS Version: Catalina
 - App Version:10.15.4

**Describe the bug**
I am using latest version of Laravel
Some tasks run well but most of the Laravel tasks don't run and some give an error at the Preparing build step, and some in the Running step, here is an example output for Remove down migration task:

```Preparing build

Deprecated: Invalid characters passed for attempted conversion, these have been ignored in phar:///opt/shift/workbench/helpers.php on line 252

Fatal error: Uncaught TypeError: Unsupported operand types: int + string in phar:///opt/shift/workbench/helpers.php:252
Stack trace:
#0 phar:///opt/shift/workbench/workbench.php(47): checksum(' 08925356-4298-...')
#1 /opt/shift/workbench(9): require('phar:///opt/shi...')
#2 {main}
  thrown in phar:///opt/shift/workbench/helpers.php on line 252
--------------
Build failed
```

**To Reproduce**
1- Launch workbench
2- Click Browse and select project path
3- Select Remove down migration task and click Run

**Comment by jasonmccreary** [comment]
This appears to be an issue with your license key, please email support to get it reset/resolved.
