### ISSUE TITLE
Refactor resource controllers to individual routes

### ISSUE THREAD

**Issue by jasonmccreary** [laravel-shift/workbench-issues#63]
**What would you like to do?**
User requested via email a task to separate a `resource` route into its individual routes.

**Before**
```php
Route::resource('photos', PhotoController::class);
```

**After**
```php
Route::get('photos', [PhotoController::class, 'index'])->name('photos.index');
Route::get('photos/create', [PhotoController::class, 'create'])->name('photos.create');
// ...
```

Note, this should respect any additional customizations via `only`, `except`, naming, etc.

**Comment by matt-h** [comment]
Maybe use the [controller grouping](https://laravel.com/docs/9.x/routing#route-group-controllers) for this?
```php
Route::controller(PhotoController::class)->group(function () {
    Route::get('photos', 'index')->name('photos.index');
    Route::post('photos/create', 'create')->name('photos.create');
    // ...
});
```

**Comment by jasonmccreary** [comment]
@matt-h, yes, that's separate in #62.

**Comment by jasonmccreary** [comment]
An "experimental" version of this task was added in `0.8.0`. The basic conversion above should work, but we'll need to continue to add support for more complex _resources_ which use additional options.
