### ISSUE TITLE
PHP tasks are failing

### ISSUE THREAD

**Issue by princejohnsantillan** [laravel-shift/workbench-issues#7]
**Desktop:**
 - OS: Mac
 - OS Version: Big Sur
 - App Version: 0.2.3

**Describe the bug**
Some tasks fail when I run them.

**To Reproduce**
Just run the following tasks
1. php/create_function
2. php/array-functions
3. php/arrow-functions
4. php/null-coalesce
5. php/convert-each
6. php/array-destructuring

Basically the same errors for all of them.

![Screen Shot 2021-07-02 at 7 51 54 PM](https://user-images.githubusercontent.com/60916966/124271191-bc2f4780-db6f-11eb-998b-c85dade714eb.png)

**Comment by jasonmccreary** [comment]
@princejohnsantillan, we've seen this issue before. It is not something within the Workbench directly, but something in the project which triggers this exception.

We'd like to diagnose what it is to build some defenses around it. Would it be possible for you to run one of these tasks against the same project using the [cloud-based Workbench](https://laravelshift.com/workbench). That will give us better logging on exactly which file is causing the issue.

**Comment by princejohnsantillan** [comment]
@jasonmccreary  this worked fine on the cloud based. 
shift-build-1619, not sure if you can track it with that but that's the branch it created for me.

**Comment by jasonmccreary** [comment]
Interesting. I wonder maybe if you have a dev dependency that's conflicting. For example PHPStan? Or LaraStan?

**Comment by princejohnsantillan** [comment]
These are the dev dependencies I have

```json
   "require-dev": {
        "barryvdh/laravel-debugbar": "^3.5",
        "facade/ignition": "^2.5",
        "fakerphp/faker": "^1.9.1",
        "filp/whoops": "^2.0",
        "friendsofphp/php-cs-fixer": "^2.19",
        "laracademy/generators": "^2.3",
        "laravel/dusk": "^6.11",
        "laravel/sail": "^1.0.1",
        "mockery/mockery": "^1.4.2",
        "nunomaduro/collision": "^5.0",
        "nunomaduro/phpinsights": "^1.14",
        "overtrue/phplint": "^2.0",
        "pdepend/pdepend": "^2.7",
        "phpbench/phpbench": "^1.0",
        "phploc/phploc": "^6.0",
        "phpmd/phpmd": "^2.8",
        "phpunit/phpunit": "^8.5.8|^9.3.3",
        "sebastian/phpcpd": "^6.0",
        "squizlabs/php_codesniffer": "^3.5"
    },
```

**Comment by jasonmccreary** [comment]
My guess is one of the other dependencies has PHPStan as a sub-dependency which is ultimately causing the error. Off the top of my head, probably `phpmd/phpmd`.

To prove this, you could run `composer install --no-dev` on your project and try using the Workbench. If that succeeds, then you could determine which dev dependency causes the conflict.

Let us know if that works and maybe we can build a work around or at least a warning if particular packages are detected.

**Comment by princejohnsantillan** [comment]
I tried ```composer install --no-dev```, this is what I got

<img width="1021" alt="Screen Shot 2021-07-04 at 9 26 20 AM" src="https://user-images.githubusercontent.com/60916966/124370628-4bda1080-dcac-11eb-8b54-e982aca32dbd.png">

**Comment by jasonmccreary** [comment]
Unfortunately, seems there's still something locally that is causing these PHP tasks to fail that is not present on the cloud-based runs.

Let me see if we can build in some kind of "debug" mode so we all get a little more hint as to why these are failing. If not, maybe we could do a short call to see as this is likely to be an issue for others.

**Comment by princejohnsantillan** [comment]
I'd be happy to help. Let me know if you want to jump on a call.

**Comment by jasonmccreary** [comment]
@princejohnsantillan, absolutely, please email support@laravelshift.com and we can set up a time.

**Comment by princejohnsantillan** [comment]
@jasonmccreary sent an email to support. Let me know if you got it.

**Comment by jasonmccreary** [comment]
There are some updates in the latest path release (0.3.2) which may help with the issue. Please try again running some of the PHP tasks again on your project and let us know if you're still receiving failures.

**Comment by princejohnsantillan** [comment]
@jasonmccreary unfortunately it's the same. 😢
![Screen Shot 2021-07-12 at 11 41 25 PM](https://user-images.githubusercontent.com/60916966/125316483-bd7c2380-e36a-11eb-8cb1-071ce75564f9.png)

**Comment by jasonmccreary** [comment]
@princejohnsantillan given these updates and the fact the cloud-based Shift ran, I believe this may have something to do with your local dependencies. Again, I think installing only your production dependencies via `composer install --no-dev` may help, as that is all the cloud-based Workbench installs.

Also, looking at the logs from that build, I do see some PSR-4 compliance issues. While these should not cause the failure, may be worth fixing them.

```txt
Class App\Http\Controllers\Api\EntityController located in ./app/Http/Controllers/API/EntityController.php does not comply with psr-4 autoloading standard. Skipping.
Class App\Models\Web\Observers\EntityObserver located in ./app/Observers/EntityObserver.php does not comply with psr-4 autoloading standard. Skipping.
```

**Comment by princejohnsantillan** [comment]
ahh perfect! `composer install --no-dev` works now.  Thanks @jasonmccreary !

**Comment by jasonmccreary** [comment]
Awesome. Glad to hear it. My guess is you have a local copy of PHPStan or another static analysis tool that is causing a conflict with the PHP tasks.
