### ISSUE TITLE
Docker shift-workbench yaml startup error

### ISSUE THREAD

**Issue by inalto** [laravel-shift/workbench-issues#70]
**Desktop:**
 - OS: [Windows]
 - OS Version: [11]
 - App Version: [0.8.3.0]

**Describe the bug**
Newly installed, i ex, Code Format error follow:

Spawning docker 
--------------
Build failed
You may review the output from the steps above for more detail. If you believe this is an error with the Workbench, please [open an issue](https://github.com/laravel-shift/workbench-issues).

>>> JSON:{"event":"step-started","data":{"heading":"Preparing build","step":"preparing-build"}}
Workbench version: 9dd24dc1437ca88693427a641107461306be5159 (2022-03-10)
Run UID: f255510a230dc695
Validating build YAML...
Failed to read the build file. Please try again. If this failure persists, please submit an issue from the "Help" menu.
>>> JSON:{"event":"step-failed","data":{"step":"preparing-build","runtime":"0.000100"}}

**To Reproduce**
Open the app and run a tool, you get an error "build failed" even if i run with administrator privileges.
Seems there is an error in some yaml file.

![immagine](https://user-images.githubusercontent.com/6382732/158588943-fd7a5075-4803-4723-aefa-846966024927.png)

**Comment by jasonmccreary** [comment]
Failure to read the build file would mean the application couldn't read from the core directory. I haven't heard any other reports of this, so I'll assume our path is not wrong. Do you have any kind of system restrictions or mounts that might prevent the app from reading the filesystem?

**Comment by inalto** [comment]
I think i have understood why is not working.
it seems that we cant use it on shared folders like \\\\10.1.1.10\something but you have to map to a drive letter.

**Comment by jasonmccreary** [comment]
I see. So is this working when you use a drive letter?

**Comment by merlin334** [comment]
Had the exact same problem.
Fixed it by turning off focus assist in windows.
Focus assist prevented the sharing of files with Docker.
![focus-assist](https://user-images.githubusercontent.com/9083576/161738760-e3af0f0c-2ffc-479c-8f19-1d9701935748.jpg)
.

**Comment by jasonmccreary** [comment]
Interesting. Thanks for following up.
