### ISSUE TITLE
Error PHP 8.1, composer ?

### ISSUE THREAD

**Issue by ElRochito** [laravel-shift/workbench-issues#71]
**Desktop:**
 - OS: Mac
 - OS Version: 12.3
 - App Version: 0.8.3

**Describe the bug**
I try to launch php/property-promotion on my project which is based on PHP 8.1 (see screenshot below)

I tried too to set php 8.0 on my composer.json et composer.lock but got same error.

![image](https://user-images.githubusercontent.com/1737307/158992585-4618f1fd-d148-4aa6-a136-914ab0a16fb9.png)

**Comment by jasonmccreary** [comment]
Yes, this is likely due to the Shift image still running 8.0. This is something we plan to make configurable before v1. Hopefully in a few weeks.

In the meantime, you may be able to get around it by removing your `php` constraint or faking it with a `config` setting.

**Comment by ElRochito** [comment]
Ok, thanks

**Comment by billriess** [comment]
Was PHP 8.1 support ever added?

**Comment by jasonmccreary** [comment]
Not yet. We're going to make the PHP version a setting in v1.0. Which we hope to release in May.

**Comment by atph** [comment]
Any updates on this one? @jasonmccreary

**Comment by jasonmccreary** [comment]
It's configurable in v1.0. We're hoping to release soon.

**Comment by jasonmccreary** [comment]
The PHP version is now configurable via the new _Preferences_ section added in v1.0.
