### ISSUE TITLE
Error on php/switch-to-match

### ISSUE THREAD

**Issue by schonhoff** [laravel-shift/workbench-issues#72]
**Desktop:**
 - OS: Windows
 - OS Version: 10
 - App Version: 0.8.3.0

Hello,

I don't know, if the issue is related to this #6 . I got an error after some time:
```
Analyzing project...
Shift detected a large project size of 601.3M
This may cause tasks to run slow under Docker's filesystem I/O. You may reduce your project size by removing any large or temporary files, or temporarily removing unrelated code, like the `node_modules` folder.
```

```
Event: Processing paths: app, database/factories, database/seeders, packages/dhl/sdk-api-express/src, packages/gkm/src/GKM, config, database/migrations, routes, tests
Failed to run rector: convert-switch-to-match: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/ConvertSwitchToMatch.php(18): Shift\Tasks\Workbench\ConvertSwitchToMatch->rector('/opt/shift/reso...')
#1 phar:///opt/shift/workbench/workbench.php(89): Shift\Tasks\Workbench\ConvertSwitchToMatch->perform()
#2 /opt/shift/workbench(9): require('phar:///opt/shi...')
#3 {main}
```

It takes really long to finish (269s). I don't really know what is causing the issue. Sorry that I can't deliver more information on the topic at the moment. Maybe it can't handle the "packages" directory with my custom packages? (It is just a guess.) Can I exclude those directories from the task and try to run it again?

Edit: I already removed node_modules directory to have a smaller project size.

**Comment by schonhoff** [comment]
I changed my .shiftrc to exclude some directories. The Problem still occur.

```
>>> Event: Processing paths: app, database/factories, database/seeders, packages/dhl/sdk-api-express/src, packages/gkm/src/GKM, config, database/migrations, routes, tests
>>> Event: Excluding: node_modules, packages/gkm/src/Certificate, packages/gkm/src/wsdl, packages/gkm/src/xsd, storage, public, vendor
Failed to run rector: convert-switch-to-match: #0 phar:///opt/shift/workbench/src/Tasks/Workbench/ConvertSwitchToMatch.php(18): Shift\Tasks\Workbench\ConvertSwitchToMatch->rector('/opt/shift/reso...')
#1 phar:///opt/shift/workbench/workbench.php(89): Shift\Tasks\Workbench\ConvertSwitchToMatch->perform()
#2 /opt/shift/workbench(9): require('phar:///opt/shi...')
#3 {main}
```
![image](https://user-images.githubusercontent.com/42345405/159051480-7bf6265d-ad2b-43e3-bae5-730bc6048e14.png)

Have the same error on some other tasks. I tried to exclude the package directory and some are working again. But that is not what I wanted. The package directory isn't even that big:
![image](https://user-images.githubusercontent.com/42345405/159053808-83f42bf9-1f48-4c6b-acac-056ffea9c8c7.png)

**Comment by jasonmccreary** [comment]
Some of the underlying free tasks rely on Rector, which is rather fickle. Especially when you have any kind of overlapping classes or functions. We've found such overlap is common within Laravel apps which might use IDE helpers or classmaps to unveil some of Laravel's automagic.

**Comment by schonhoff** [comment]
I'm just using the barryvdh/laravel-ide-helper as an IDE helper. May that cause the issue?
Many other tasks are running without a problem (and in lower than 10 seconds) but this task and "nullsafe Operator" are running very slow. 
Is there any "fix" to run the tasks or should I don't use those tasks at the moment?

Thanks for the very fast reply! :) Great tool and great support (also love the Laravel Shift weeklies, helped me out a ton!)

**Comment by jasonmccreary** [comment]
Yes, something like the `ide_helper` file could definitely throw off static analysis tools. However, it might not be the only problem.

Yes, unfortunately both these tasks are ones backed by Rector. We plan to remove the Rector integration as it's proven to be quite buggy.

**Comment by jasonmccreary** [comment]
As this is one of the free tasks backed by Rector, it is not something we support directly. You are welcome to try and run this task directly in your application via Rector. If that fails, you should [open a Rector issue](https://github.com/rectorphp/rector/issues).

Alternatively, you may try running the [cloud-based Workbench](https://laravelshift.com/workbench) to rule out any local dependency issues. If that succeeds, it's likely you have a local file or dependency which conflicts with Rector.
