### ISSUE TITLE
Build failed without detail info

### ISSUE THREAD

**Issue by mberneis** [laravel-shift/workbench-issues#75]
**Desktop:**
 - OS:Mac
 - OS Version: 12.3
 - App Version: Workbench 0.8.3
 - 
**Describe the bug**
I ran the new-in-initializer task via docker on my code and got a build fail without any other information

**To Reproduce**
3. Run '....'

![image](https://user-images.githubusercontent.com/30384/161872639-9ad44b14-d92c-46f0-8d7a-f7859f918331.png)

**Comment by jasonmccreary** [comment]
Some of these tasks are rather "black box". We have a task to improve the output for v1.0. In the meantime, if you want to try the cloud-based Workbench, we can see if there are some more details. Just reply back with the build number.

**Comment by mberneis** [comment]
It worked fine in the cloud based workbench - closing it

**Comment by jasonmccreary** [comment]
Interesting. I still wonder why it failed locally. But @jessarcher and I are working to improve both the failure and success messaging in a separate task. So hopefully that will help in the future.
