### ISSUE TITLE
Use Laravel Carbon issue

### ISSUE THREAD

**Issue by khanalpride** [laravel-shift/workbench-issues#77]
App Version: 0.8.3

**Describe the bug**
Updates the `use Carbon\CarbonPeriod'` to `use Illuminate\Support\CarbonPeriod;`.

**To Reproduce**
1. Run workbench
2. Run Use Laravel Carbon

**Comment by jasonmccreary** [comment]
Thanks. I'll get this fixed up.

**Comment by jasonmccreary** [comment]
This is fixed in release 0.9.0.
