### ISSUE TITLE
Controller Validation task returns empty output

### ISSUE THREAD

**Issue by JeffreyDavidson** [laravel-shift/workbench-issues#79]
**Desktop:**
 - OS: Mac 
 - OS Version: Monterey
 - App Version: 0.9.3

**Describe the bug**
Provide a short description of the bug. Just a sentence or two.

I tried to run the Controller Validation task and after running it I got the error below as shown in the image.

**To Reproduce**
1. Go to 'Controller Validation task'
2. Click on 'run'
3. See error as shown in image

<img width="1022" alt="Screen Shot 2022-05-19 at 10 14 49 AM" src="https://user-images.githubusercontent.com/3826104/169315237-03d9e676-a7fd-473f-9f38-8b703ed92c58.png">

**Comment by jasonmccreary** [comment]
Does it run for you on the cloud-based Workbench?

**Comment by JeffreyDavidson** [comment]
It does run on the cloud-based Workbench!

**Comment by jasonmccreary** [comment]
Good. I'm not sure the issue locally. For whatever reason, sometimes these same tasks fail within the desktop app. It's likely something with the environment or local setup.

We're adding more debugging options for v1 as it's impossible to know right now.
