### ISSUE TITLE
Controller Validation

### ISSUE THREAD

**Issue by HDVinnie** [laravel-shift/workbench-issues#80]
**Desktop:**
 - OS: Mac
 - OS Version: 12.2.1
 - App Version: 0.9.3

**Describe the bug**
```
class method returned empty output: #0 phar:///opt/shift/workbench/workbench.php(89): Shift\Tasks\Laravel\Fixer\ConvertControllerValidation->perform()
#1 /opt/shift/workbench(9): require('phar:///opt/shi...')
#2 {main}
```

**To Reproduce**
1. Go to Workbench app.
2. Click on laravel/form-request
3. Run it

**Comment by jasonmccreary** [comment]
Does this work on the cloud-based Workbench?
