### ISSUE TITLE
Code format - pint not found

### ISSUE THREAD

**Issue by scottdsnr** [laravel-shift/workbench-issues#82]
- OS: Windows (WSL)
 - OS Version: 10
 - App Version:  1.0.2

**Describe the bug**
Code formatter not completing. Other tasks are working
Error message from output
![image](https://user-images.githubusercontent.com/58791337/189362238-5dd9c7e8-24d5-4e30-bd2c-7bfd90f7c5fa.png)

**To Reproduce**
Run code format with project files from WSL

**Comment by jasonmccreary** [comment]
Just released 1.0.3 which includes `laravel/pint`. Let me know if you still experience this problem.
