### ISSUE TITLE
Unsupported operand types: int + string

### ISSUE THREAD

**Issue by CrazyBoy49z** [laravel-shift/workbench-issues#83]
**Desktop:**
 - OS: Mac
 - OS Version: Monterey
 - App Version: 12.6

**Describe the bug**
```
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in phar:///opt/shift/workbench/helpers.php on line 270

Fatal error: Uncaught TypeError: Unsupported operand types: int + string in phar:///opt/shift/workbench/helpers.php:270
Stack trace:
#0 phar:///opt/shift/workbench/workbench.php(43): checksum(' 175560ea-d237-...')
#1 /opt/shift/workbench(9): require('phar:///opt/shi...')
#2 {main}
  thrown in phar:///opt/shift/workbench/helpers.php on line 270
--------------
Build failed
```

**To Reproduce**
1. Go to '[Adopt early returns]'
2. Run

**Comment by jasonmccreary** [comment]
From the partial stack trace, it seems your license key has a prefixing space. Please ensure you did not copy/paste this incorrectly.

**Comment by CrazyBoy49z** [comment]
Thanks, the problem is reinstalling the key. Due to the fact that the previous license was removed. Maybe the same problem #81

**Comment by chrisdicarlo** [comment]
Thanks!  The space issue with the license key was the cause for me, as well.
