### ISSUE TITLE
Workbench with packages: Failed to find artisan

### ISSUE THREAD

**Issue by dillingham** [laravel-shift/workbench-issues#88]
**What would you like to do?**
In trying to update a package that has controllers and such, I ran the workbench and got the following output

```
Preparing build
Analyzing project...
Failed to find artisan
--------------
Build failed
```
Im guessing you rely heavily on the laravel structure to perform these tasks. I just was hoping to do things like switch to array validation rules etc.

**Comment by jasonmccreary** [comment]
Most of these tasks are for a Laravel application, not a package. There are ways to try and hack it if the structure is similar to an application. For example, dropping in an empty `artisan` file.

**Comment by dillingham** [comment]
Yeah I figured as much, just wishful thinking haha I'll give that a try thanks!
